CREATE TABLE PROFESSORES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR2(128) NOT NULL,
    SOBRENOME VARCHAR2(128) NOT NULL,
    ENDERECO VARCHAR2(500),
    TELEFONE VARCHAR2(128),
    EMAIL VARCHAR2(128),
    DATA_NASCIMENTO DATE,
    GENERO VARCHAR2(128) NOT NULL,
    CIDADE VARCHAR2(128) NOT NULL,
    ESTADO VARCHAR2(128),
    NACIONALIDADE VARCHAR2(128),
    PRIMARY KEY(ID)
);

CREATE TABLE ESTUDANTES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR2(128) NOT NULL,
    SOBRENOME VARCHAR2(128) NOT NULL,
    MATRICULA VARCHAR2(128),
    EMAIL VARCHAR2(128),
    DATA_NASCIMENTO DATE,
    GENERO VARCHAR2(128),
    CIDADE VARCHAR2(128),
    ESTADO VARCHAR2(128),
    NACIONALIDADE VARCHAR2(128),
    MEDIA_GERAL NUMBER(4,2),
    PRIMARY KEY(ID)
);

CREATE TABLE CURSOS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CODIGO VARCHAR2(128),
    NOME VARCHAR2(128),
    EAD CHAR(1), -- 0 = FALSO / 1 = VERDADEIRO
    ID_PROFESSOR NUMBER NOT NULL,
    NUMERO_MAXIMO_ALUNOS NUMBER,
    PRIMARY KEY(ID),
    FOREIGN KEY(ID_PROFESSOR) REFERENCES PROFESSORES(ID) -- limita as escolhas aos IDs existentes
);

CREATE TABLE MATRICULAS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_ESTUDANTE NUMBER,
    ID_CURSO NUMBER,
    MEDIA_ALUNO NUMBER(4,2),
    PRIMARY KEY(ID),
    FOREIGN KEY(ID_ESTUDANTE) REFERENCES ESTUDANTES(ID),
    FOREIGN KEY(ID_CURSO) REFERENCES CURSOS(ID)
);

-- Inserindo dados dos Professores
INSERT INTO PROFESSORES (nome, sobrenome, endereco, telefone, email, data_nascimento, genero, cidade, estado, nacionalidade)
VALUES ('George', 'Bravo', 'Av. Conselheiro Nébias', '99887-7665', 'georgebravo@gmail.com', '28/04/1994', 'Masculino', 'Santos', 'SP', 'Brasileiro');
INSERT INTO PROFESSORES (nome, sobrenome, endereco, telefone, email, data_nascimento, genero, cidade, estado, nacionalidade)
VALUES ('Júlio', 'Horto', 'Rua Bauruense', '99887-7665', 'juliohorto@gmail.com', '15/09/1982', 'Masculino', 'Bauru', 'SP', 'Brasileiro');
INSERT INTO PROFESSORES (nome, sobrenome, endereco, telefone, email, data_nascimento, genero, cidade, estado, nacionalidade)
VALUES ('Astrid', 'Hannah', 'Av. Nações Unidas', '91122-3344', 'analyvia@gmail.com', '12/06/1996', 'Feminino', 'Buenos Aires', 'Buenos Aires', 'Argentina');
INSERT INTO PROFESSORES (nome, sobrenome, endereco, telefone, email, data_nascimento, genero, cidade, estado, nacionalidade)
VALUES ('William', 'Gomes', 'Rua Cipó', '98765-1223', 'williamgomes@gmail.com', '01/03/1993', 'Masculino', 'Porto Alegre', 'RS', 'Brasileiro');
INSERT INTO PROFESSORES (nome, sobrenome, endereco, telefone, email, data_nascimento, genero, cidade, estado, nacionalidade)
VALUES ('Lionel', 'West', 'Rua Americana', '99009-0990', 'lionelwest@gmail.com', '22/10/1945', 'Masculino', 'Smallville', 'Kansas', 'Americano');


-- Inserindo dados dos Estudantes
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Tiago', 'Rezende', '195', 'tiagoviniciusrezende@simsvale.com.br', '18/02/2004', 'Masculino', 'Tubarão', 'SC', 'Brasileiro', 10.0);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Enrico', 'Santos', '123', 'enrico_dossantos@edpbr.com.br', '16/03/1999', 'Masculino', 'Belo Jardim', 'PE', 'Brasileiro', 3.5);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Rebeca', 'Lavínia', '162', 'rebeca_lavinia_jesus@i9pneus.com.br', '06/03/1971', 'Feminino', 'Araras', 'SP', 'Brasileiro', 7.5);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Otávio', 'Luz', '238', 'otavio.marcio.daluz@yahoo.se', '23/02/1986', 'Masculino', 'Picos', 'PI', 'Brasileiro', 4.5);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Joana', 'Moraes', '225', 'joana.moraes@argo.com.br', '15/02/1993', 'Feminino', 'Macapá', 'AP', 'Brasileiro', 8.5);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Isabelly', 'Cavalcanti', '293', 'isabelly_cavalcanti@tanby.com.br', '09/01/1984', 'Feminino', 'Macapá', 'AP', 'Brasileiro', 6.0);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Lorenzo', 'Jesus', '345', 'lorenzo_jesus@mpv.org.br', '06/03/1977', 'Masculino', 'Rio Branco', 'AC', 'Brasileiro', 1.0);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Eduarda', 'Galvão', '321', 'eduarda-galvao80@gimail.com', '02/01/1956', 'Feminino', 'Várzea Grande', 'MT', 'Brasileiro', 9.5);
INSERT INTO ESTUDANTES (nome, sobrenome, matricula, email, data_nascimento, genero, cidade, estado, nacionalidade, media_geral)
VALUES ('Samuel', 'Fernandes', '309', 'samuel-fernandes78@arablock.com.br', '22/02/2004', 'Masculino', 'Araguaína', 'TO', 'Brasileiro', 5.5);

-- Inserindos dados dos Cursos
INSERT INTO CURSOS (codigo, nome, ead, id_professor, numero_maximo_alunos)
VALUES ('C1', 'ALGORITMOS', 0, 1, 15);
INSERT INTO CURSOS (codigo, nome, ead, id_professor, numero_maximo_alunos)
VALUES ('C2', 'BANCO DE DADOS', 1, 2, 30);
INSERT INTO CURSOS (codigo, nome, ead, id_professor, numero_maximo_alunos)
VALUES ('C3', 'JAVA', 0, 3, 45);
INSERT INTO CURSOS (codigo, nome, ead, id_professor, numero_maximo_alunos)
VALUES ('C4', 'SISTEMAS', 1, 3, 45);
INSERT INTO CURSOS (codigo, nome, ead, id_professor, numero_maximo_alunos)
VALUES ('C5', 'ANGULAR', 0, 5, 20);

-- Inserindo dados das Matrículas
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (1, 1, 10.0);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (2, 1, 3.0);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (3, 1, 8.0);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (4, 2, 5.0);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (5, 2, 8.5);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (6, 2, 7.5);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (7, 3, 2.0);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (8, 3, 9.0);
INSERT INTO MATRICULAS (id_estudante, id_curso, media_aluno)
VALUES (9, 3, 6.0);

COMMIT;

-- Ex 5
UPDATE ESTUDANTES SET MEDIA_GERAL = 4.0 WHERE ID = 2;

UPDATE CURSOS SET EAD = '1' WHERE ID_PROFESSOR IN (SELECT ID FROM PROFESSORES WHERE ESTADO <> 'SC');

DELETE FROM CURSOS WHERE NOME = 'SISTEMAS';
COMMIT;


-- Ex 6
SELECT * FROM CURSOS WHERE NUMERO_MAXIMO_ALUNOS > 30 AND EAD = '0';

SELECT * FROM PROFESSORES WHERE NACIONALIDADE IN ('Brasileiro', 'Argentino', 'Colombiano');

SELECT * FROM ESTUDANTES WHERE NOME LIKE 'J%';

SELECT * FROM ESTUDANTES WHERE MEDIA_GERAL > 7 ORDER BY MEDIA_GERAL DESC;

SELECT * FROM CURSOS C
    JOIN PROFESSORES P ON C.ID_PROFESSOR = P.ID
    WHERE P.GENERO = 'Feminino';
    
SELECT E.* FROM ESTUDANTES E
    JOIN MATRICULAS M ON E.ID = M.ID_ESTUDANTE
    JOIN CURSOS C ON M.ID_CURSO = C.ID
    WHERE C.EAD = '1';